#!/usr/bin/env ruby
#: ft=ruby

$LOAD_PATH << Pathname.new(__FILE__).parent.join("lib")

require "homography_experiment"

def motueka_three( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/three" ).join(file).expand_path
end
def motueka_four( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/four" ).join(file).expand_path
end

exp = HomographyExperiment.from_opts { |exp|
  exp.feature_library.do_normalize = false

  exp.image_pairs.add motueka_four( "IMG_7654.jpg" ), motueka_four("IMG_7655.jpg") 
  #exp.image_pairs.add motueka_three( "IMG_7423.jpg" ), motueka_three("IMG_7424.jpg") 
}

exp.dump
exp.run


