#!/usr/bin/env ruby

$LOAD_PATH << Pathname.new(__FILE__).parent.join("lib")

require "homography_experiment"

def motueka_one( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/one" ).join(file).expand_path
end
def motueka_three( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/three" ).join(file).expand_path
end
def motueka_four( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/four" ).join(file).expand_path
end

exp = HomographyExperiment.from_opts { |exp|
  img_7622 = InputImage.new( motueka_four( "IMG_7622.jpg" ) )
  img_7621 = InputImage.new( motueka_four( "IMG_7621.jpg" ) )
  origin = InputImage.new( motueka_four( "IMG_7620.jpg" ) )

  img_7423 = InputImage.new motueka_three( "IMG_7423.jpg" )
  one_6367 = InputImage.new motueka_one( "IMG_6367.jpg" )

  exp.image_pairs.add img_7621, one_6367

  #exp.image_pairs.add img_7621, img_7622

  #exp.image_pairs.add img_7423, origin
  #exp.image_pairs.add img_7423, img_7622

  #exp.image_pairs.add motueka_four( "IMG_7622.jpg" ), motueka_three("IMG_7422.jpg")
  #exp.image_pairs.add motueka_four( "IMG_7622.jpg" ), motueka_one("IMG_6365.jpg")
}

exp.dump
exp.run


