#!/usr/bin/env ruby
#: ft=ruby

$LOAD_PATH << Pathname.new(__FILE__).parent.join("lib")

require "flann_experiment"

def motueka_four( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/four" ).join(file).expand_path
end

exp = FlannExperiment.from_opts { |exp|

  exp.add_pair( motueka_four( "IMG_7654.jpg" ), motueka_four("IMG_7655.jpg") )

  exp.algorithms << BruteForceMatcher.new

}

exp.dump
exp.run


