#!/usr/bin/env ruby

$LOAD_PATH << Pathname.new(__FILE__).parent.join("lib")

require "flann_experiment"

def motueka_four( file )
  Pathname.new( "~/workspace/aerial_data_sets/motueka_quarter_scale/four" ).join(file).expand_path
end

exp = FlannExperiment.from_opts { |exp|

  exp.add_pair( motueka_four( "IMG_7654.jpg" ), motueka_four("IMG_7655.jpg"),
               h:  [[ 1.01912e+00, -1.53479e-02, -5.10015e+01 ],  
                    [2.72249e-03,  9.98174e-01, -1.26761e+02 ], 
                    [3.09099e-05, -5.04486e-05,  1.00000e+00 ]]  )

  exp.algorithms << (exp.reference = BruteForceMatcher.new)
  exp.algorithms << RiceFlannMatcher.new

  weight = 1000000.0;
  weight = weight.to_f / 972.0;     # 972 is the width of the test images.

  exp.algorithms << EnhancedFlannMatcher.new( weight )

}

exp.dump
exp.run


